name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print GITHUB_WORKSPACE
        run: echo "Workspace:$GITHUB_WORKSPACE"

      - name: Fetch SSH Key
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > $HOME/.ssh/id_rsa.pub
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa $HOME/.ssh/id_rsa.pub
          ls -la $HOME/.ssh

      - name: Terraform Validate
        run: |
          cd $GITHUB_WORKSPACE
          terraform validate

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform Configuration
        run: terraform validate

      - name: Plan Terraform Changes
        run: terraform plan -out=tfplan

  deploy:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Apply Terraform Changes
        run: terraform apply -auto-approve tfplan

      - name: Cleanup
        run: rm -rf .terraform

  cleanup:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Destroy Terraform Resources
        run: terraform destroy -auto-approve
        working-directory: ${{ github.workspace }}
        env:
          TF_VAR_gcp_project: ${{ secrets.GCP_PROJECT }}
          TF_VAR_gcp_region: ${{ secrets.GCP_REGION }}

      - name: Cleanup Workspace
        run: rm -rf .terraform